<?php

$_ACESSO = 'Acesso';
$_ATENCAO = 'Atenção';
$_CADASTROS_EFETUADOS = 'cadastro(s) efetuado(s).';
$_CHAMAEUKATWO = 'Chama Eu Katwo!';
$_COLABORAR = 'Colaborar';
$_COMO_FUNCIONA = 'Como funciona';
$_COMO_FUNCIONA .=('&nbsp;<span class="glyphicon glyphicon-share-alt"></span>&nbsp;');
$_COMO_FUNCIONA .=('ChamaEuKatwo?');
$_CONTATO = 'Contato';
$_COPIAR = 'Copiar';
$_DICAS_IMPORTANTES = 'Dicas importantes!';
$_EITA_CALMA_AI_VEI = 'Eeeiittaaa! de novo? Calma, espera chamar pow!';
$_EXCLUIR = 'Excluir';
$_FECHAR = 'Fechar';
$_FIQUE_ATENTO_A_LIVE = 'Fique atento acompanhando a live, caso contrário quando for chamado poderá perder sua vez!';
$_INICIAL = 'Inicial';
$_INSCRICOES_ABERTAS = ('Mantenha inscrições sempre abertas');
$_JA_CADASTRADO = 'Já cadastrado';
$_JOGO = 'Jogo';
$_NICKNAME = 'Nick Name';
$_NOME_YOUTUBE = 'Nome YouTube';
$_NOVO_DIA_NOVOS_INSCRITOS = 'Novo dia, novos inscritos.';
$_PATROCINADORES = 'Patrocinadores';
$_PEGUE_SEU_AGORA = 'Pegue o seu agora!';
$_PREENCHA_CAMPOS_OBRIGATORIOS = '*Preencha os campos obrigatórios';
$_PROJETOS = 'Projetos';
$_QUER_AJUDAR = 'Quer Ajudar?';
$_SAIR = 'Sair';
$_SEJA_COLABORADOR = 'Seja um colaborador!';
$_SEU_LINK_YOUTUBE = 'Seu Link no Youtube <span style="color:#808080;">[ *conferir inscrição ]</span>';
$_SOBRE = 'Sobre';
$_STATUS = 'Status';
$_TODOS_CAMPOS_PREENCHIDOS = '* Todos os campos devem ser preenchidos.';
$_USUARIO_BANIDO = 'Usuário banido';


$_TXT_ACCORDION_DICAS_IMPORTANTES ='';

$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('ul',NULL,'li');
$_TXT_ACCORDION_DICAS_IMPORTANTES .=('<b>Cadastre seus dados corretamente</b>.');
$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_DICAS_IMPORTANTES .=('É fundamental que você esteja acompanhado a transmissão do canal.');
$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_DICAS_IMPORTANTES .=('Mantenha seu jogo aberto e esteja logado.');
$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_DICAS_IMPORTANTES .=('Se você for chamado para uma partida e não estiver "ligado", perderá a vez.');
$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_DICAS_IMPORTANTES .=('Não seja um jogador tóxico, <b style="color:red;">criticas e ofensas aos demais jogadores não serão tolerados</b>.');
$_TXT_ACCORDION_DICAS_IMPORTANTES .= $katwo->duasTags('/li',NULL,'/ul');


$_TXT_ACCORDION_COMO_FUNCIONA = $katwo->duasTags('ul',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('<b>Jogando com inscritos [Amigos]</b>');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->Tags('br');
$_TXT_ACCORDION_COMO_FUNCIONA .=('<a data-toggle="modal" href="#inscricoesAbertas">');
$_TXT_ACCORDION_COMO_FUNCIONA .=('É necessário que você deixe suas inscrições públicas no Youtube. Como? <b>Clique Aqui!</b>');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->Tags('/a');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Ao finalizar uma partida o próximo time será chamado de acordo com os cadastros neste sistema.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Os amigos serão chamados por ordem de cadastro na lista.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('A lista é válida apenas para o dia de hoje: <b style="font-size:2.0em">'.$exibedatahoje.'</b>');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Caso a Stream seja em horário que possa mudar o dia, a lista automáticamente irá ZERAR os registros, dando início à uma nova relação de amigos.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('<b>A fila anda</b>: Se você perder a vez, deverá cadastrar um novo pedido de participação.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Não seja um jogador tóxico, <b  style="color:red;">críticas e ofensas aos demais jogadores/participantes da live não serão tolerados</b>.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('<b style="font-size:2.0em; color:#800000;">STATUS:</b>');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->Tags('br');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Se "<b>Ativo</b>", você ainda deverá ser chamado.');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->Tags('br');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Se "<b>Inativo</b>", você:');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('ul',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Já jogou;');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Já foi chamado e não respondeu estava online;');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Fornceceu dados incorretos;');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Não está inscrito no canal KatwoGamer;');
$_TXT_ACCORDION_COMO_FUNCIONA .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_COMO_FUNCIONA .=('Sua inscrição no canal KatwoGamer não está visível;');
$_TXT_ACCORDION_COMO_FUNCIONA .= $katwo->duasTags('/li',NULL,'/ul');
$_TXT_ACCORDION_COMO_FUNCIONA .= $katwo->duasTags('/li',NULL,'/ul');

$_TXT_ACCORDION_QUER_AJUDAR =$katwo->duasTags('ul',NULL,'li');
$_TXT_ACCORDION_QUER_AJUDAR .=('<b>Likes</b> são um importante recurso para ajudar o canal a crescer, então lembre-se de dar seu tapa no like a cada nova Stream.');
$_TXT_ACCORDION_QUER_AJUDAR .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_QUER_AJUDAR .=('<b>Compartilhar</b> as transmissões é muito importante para divulgação do trabalho. Sempre que puder, compartilhe!');
$_TXT_ACCORDION_QUER_AJUDAR .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_QUER_AJUDAR .=('<b>Mensagens na Tela</b>: Use o <b>LOOTS</b> para ver suas mensagens em destaque diretamente na tela da transmissão.');
$_TXT_ACCORDION_QUER_AJUDAR .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_QUER_AJUDAR .=('<b>Super Chat:</b> uma forma de contribuir financeiramente com valores que você mesmo determina.');
$_TXT_ACCORDION_QUER_AJUDAR .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_QUER_AJUDAR .=('<b>Patrocinador</b>: Recurso disponibilizado pelo Youtube para que você contribua mensalmente com o trabalho do canal.');
$_TXT_ACCORDION_QUER_AJUDAR .=$katwo->duasTags('/li',NULL,'/ul');

$_TXT_ACCORDION_SOBRE =$katwo->duasTags('ul',NULL,'li');
$_TXT_ACCORDION_SOBRE .=('<b>Jogando com inscritos [Amigos]</b>');
$_TXT_ACCORDION_SOBRE .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_SOBRE .=('Caso ainda não saiba, jogamos por diversão e não para competir. Não temos a pretensão de jogarmos profissionalmente.');
$_TXT_ACCORDION_SOBRE .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_SOBRE .=('Queremos apenas nos divertir, encontrar os bons amigos e fazer novas amizades.');	
$_TXT_ACCORDION_SOBRE .=$katwo->duasTags('/li',NULL,'li');
$_TXT_ACCORDION_SOBRE .=('Nosso objetivo é passar as horas com muita diversão em boa companhia.');	
$_TXT_ACCORDION_SOBRE .=$katwo->duasTags('/li',NULL,'/ul');

$_TXT_COLABORADORES =('Deseja de alguma forma contribuir para o trabalho da KatwoGamer?');
$_TXT_COLABORADORES .= $katwo->tags('br',NULL,2);
$_TXT_COLABORADORES .=$katwo->duasTags('ul',NULL,'li');
$_TXT_COLABORADORES .=('<b>Likes</b> são um importante recurso para ajudar o canal a crescer, então lembre-se de dar seu tapa no like a cada nova Stream.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b>Compartilhar</b> as transmissões é muito importante para divulgação do trabalho. Sempre que puder, compartilhe!');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b>Mensagens na Tela</b>: Use o <b>LOOTS</b> para ver suas mensagens em destaque diretamente na tela da transmissão.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b>Super Chat:</b> uma forma de contribuir financeiramente com valores que você mesmo determina.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b>Patrocinador</b>: Recurso disponibilizado pelo Youtube para que você contribua mensalmente com o trabalho do canal.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b>Google Play</b>: Criamos e disponibilizamos jogos e apps gratuitos, uma boa forma de nos ajudar e se divertir.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'li');
$_TXT_COLABORADORES .=('<b class="text-danger">Lembre-se</b>: Faça uma boa resenha e dê uma boa avaliação nos nossos apps no Google Play, precisamos muito desse apoio para que o trabalho seja conhecido.');
$_TXT_COLABORADORES .=$katwo->duasTags('/li',NULL,'/ul');

$_TXT_CONTATOS =('Deseja de alguma forma contribuir para o trabalho da KatwoGamer?');
$_TXT_CONTATOS .= $katwo->tags('br');
$_TXT_CONTATOS .=$katwo->duasTags('ul',NULL,'li');
$_TXT_CONTATOS .=('Quer Fazer uma parceria?');
$_TXT_CONTATOS .=$katwo->duasTags('/li',NULL,'li');
$_TXT_CONTATOS .=('Promover seu canal?');
$_TXT_CONTATOS .=$katwo->duasTags('/li',NULL,'li');
$_TXT_CONTATOS .=('Divulgar seu Produto?');
$_TXT_CONTATOS .=$katwo->duasTags('/li',NULL,'li');
$_TXT_CONTATOS .=('Conhecer nossos jogos?');
$_TXT_CONTATOS .=$katwo->duasTags('/li',NULL,'/ul');
$_TXT_CONTATOS .= $katwo->tags('br');
$_TXT_CONTATOS .=('Envie uma mensagem para:');
$_TXT_CONTATOS .= $katwo->tags('br');
$_TXT_CONTATOS .=('<b>contatokatwogamer<img src="imagens/icones/mail_arrob.png">gmail.com</b>');
$_TXT_CONTATOS .= $katwo->tags('br');

$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE = ('Para manter suas inscrições públicas no Youtube você deverá configurar corretamente seu perfil');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('br');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Acesse as configurações de privacidade para controlar e marque a opção:');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('br');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('"Manter todas as minhas inscrições públicas".');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('br');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('h3',NULL,1,'style="color:#800000;"');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Não entendeu?');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('/h3');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('b');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Explicando de outra forma:');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('/b');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->tags('br');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Para manter as suas inscrições <b>públicas</b> no YouTube, siga estes passos:');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->duasTags('ul',NULL,'li');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Entra no seu canal do YouTube e clique em Configurações (ícone de engrenagem)<span class="glyphicon glyphicon-cog"></span>.'); 
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->duasTags('/li',NULL,'li');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Em seguida, clique em Configurações YouTube: ');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->duasTags('/li',NULL,'li');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Clique em Privacidade e na Seção Assinaturas, marque a opção:<br/> "<i>Manter todas as minhas assinaturas como públicas!</i>" ');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= $katwo->duasTags('/li',NULL,'/ul');
$_TXT_MANTER_INSCRICOES_ABERTAS_YOUTUBE .= ('Clique em Salvar. Prontinho! ');

$_TXT_PATROCINADORES = 'Deseja de alguma forma contribuir para o trabalho da KatwoGamer?';
$_TXT_PATROCINADORES .= $katwo->tags('br',NULL,2);
$_TXT_PATROCINADORES .= 'Dispomos de alguns recursos simples, gratuitos e ou de baixo custo que, com certeza, você poderá se tornar um de nossos patrocinadores.';
$_TXT_PATROCINADORES .= $katwo->tags('br',NULL,2);

$_TXT_PROJETOS =('Você já conhece nossos Jogo?<br/>');
$_TXT_PROJETOS .= $katwo->tags('br');
$_TXT_PROJETOS .=('Temos mais de 20 jogos e aplicativos publicados no Google Play.');
$_TXT_PROJETOS .= $katwo->tags('br');
$_TXT_PROJETOS .=('Muitos deles são gratuitos e você poderá mesmo assim nos ajudar se divertindo diariamente.');
$_TXT_PROJETOS .= $katwo->tags('br');
?>